$:
  vscode:
    - runner:
        cpus: 16
        memory: 32G
      services:
        - vscode
      docker:
        # 替换为1.82及以上版本，支持edition2024
        image: rust:1.82-slim
        volumes:
          - cargo_registry:copy-on-write
          - target:copy-on-write
      stages:
        - name: 配置国内Crates镜像
          script:
            - mkdir -p ~/.cargo
            - echo '[source.crates-io]' >> ~/.cargo/config.toml
            - echo 'replace-with = "rsproxy"' >> ~/.cargo/config.toml
            - echo '[source.rsproxy]' >> ~/.cargo/config.toml
            - echo 'registry = "https://rsproxy.cn/crates.io-index"' >> ~/.cargo/config.toml
        - name: 预装Rust组件
          script: rustup component add rustfmt clippy rust-src
