[fuse]
mount_point = "/mnt/powerfs"
master_addresses = ["172.20.0.11:9333", "172.20.0.12:9333", "172.20.0.13:9333"]
# filer_addresses = ["172.20.0.35:8889", "172.20.0.36:8889"]
collection = "default"
replication = "000"
threads = 8
verbose = true
container = true
log_file = "/var/log/powerfs-fuse.log"
