[global]
log_level = "info"
redis_url = "redis://crdt-redis:6379"

[volume]
grpc_port = 8080
http_port = 8091
data_dir = "/data"
node_id = "volume-server-1"
master_addresses = ["172.31.0.11:9333"]
max_volume_size = 1099511627776
initial_volume_count = 2
